### ISSUE TITLE
evaluate bash in environment variables?

### ISSUE THREAD

**Issue by joe-at-startupmedia** [datarootsio/cheek#194]
I have an edge case where I need to pass the hostname to the script as an environment variable. There is however no way to interpret the variable, currently it's just a static string. For example:
 ```yaml
purge_tokens:
    cron: 15 00  * * *
    command:
        - /usr/local/bin/node
        - /home/api_user/serve/useful-api/server/jobs/access_tokens_purge_expired_by_subscription.js
    name: access_tokens_purge_expired_by_subscription
    env:
        DEBUG: "false"
        HOSTNAME: $(hostname)
```

Hostname doesn't evaluate here.

In another approach which I assumed might have worked based on your example https://github.com/datarootsio/cheek/blob/fe435446c838feca9b0bba7890ecc2ed0e3be205/README.md?plain=1#L49 was using output chaining but this doesn't work.
 ```yaml
hostname_str:
    command: hostname
purge_tokens:
    cron: 15 00  * * *
    command:
        - /usr/local/bin/node
        - /home/api_user/serve/useful-api/server/jobs/access_tokens_purge_expired_by_subscription.js
    name: access_tokens_purge_expired_by_subscription
    env:
        DEBUG: "false"
        HOSTNAME: $hostname_str
```

How I've got it working was abstracting the executor likeso:
 ```yaml
purge_tokens:
    cron: 15 00  * * *
    command:
        - /home/api_user/serve/bin/node_exec
        - /home/api_user/serve/useful-api/server/jobs/access_tokens_purge_expired_by_subscription.js
    name: access_tokens_purge_expired_by_subscription
    env:
        DEBUG: "false"
        HOSTNAME: $(hostname)
``` 

Contents of `/home/api_user/serve/bin/node_exec`
```bash
#!/usr/bin/env bash
HOSTNAME=$(hostname)  /usr/local/bin/node
```
