### ISSUE TITLE
healthcheck endpoint

### ISSUE THREAD

**Issue by joe-at-startupmedia** [datarootsio/cheek#195]
It would be useful to provide an endpoint that returns success based on whether all currently configured jobs have recently executed successfully. It seems like you can achieve something similar by placing the above at the toplevel:
```yaml
on_error:
  notify_webhook:
    - https://webhook.site/e33464a3-1a4f-4f1a-99d3-743364c6b10f
```

But this will require the following:
* To be notified whenever an error happens
* Must have a webhook configured

My newly proposed endpoint would allow you to poll cheek on a configured basis and notify when any jobs have recently failed. This way I can notify myself via: 
*  an intermittently polling nagios check (or whatever polling alert solution you use)
* using cheek to run a bash script everyday to notify me when any of the latest jobs have failed
