### ISSUE TITLE
allow to push status messages to (slack-ish) webhook

### ISSUE THREAD

**Issue by Bart6114** [datarootsio/cheek#2]

**Comment by Bart6114** [comment]
This is hard to make generic, perhaps we just target something that is zapier compatible for now?

See below for an idea.

```
jobs:
  my_job:
    command: date
    cron: "* * * * *"
    on_success:
      trigger_jobs:
        - another_job
    on_error:
      notify:
        - zapier
zapier:
  your:
  config:
```

If we go the route of having config like this around Zapier and stuff in here we might want to leverage Viper for this as well. That way we can pass needed creds etc as env vars.
