### ISSUE TITLE
allow some schedule specs to be specified at global level

### ISSUE THREAD

**Issue by Bart6114** [datarootsio/cheek#32]
consider eg. the `notify_webhook`s

```
jobs:
  frequent_postgres_sync:
    command:
      - python
      - -m
      - scheduler.run
      - frequent_postgres_sync
    cron: "@15minutes"
    retries: 1
    on_error:
      notify_webhook:
        - https://hooks.zapier.com/hooks/catch/1948773/b9tdv8t/
  daily_postgres_sync:
    command:
      - python
      - -m
      - scheduler.run
      - daily_postgres_sync
    cron: "5 2 * * *"
    retries: 1
    on_error:
      notify_webhook:
        - https://hooks.zapier.com/hooks/catch/1948773/b9tdv8t/
```
